name: xsuite
channels:
  - conda-forge
dependencies:
  - python=3.12
  - compilers
  - setuptools=80.9.0
  - ipywidgets=8.1.7
  - ipympl
  - pint=0.25
  - pip
  - pip:
    - xsuite==0.40.0
    - xtrack==0.93.0
    - xpart==0.23.1
    - xfields==0.25.2
    - xobjects==0.5.3
    - xcoll==0.6.6
    - xplt==0.12.0
    - xwakes==0.2.5
    - py-bobyqa==1.5.0
    - cpymad==1.17.0
    - scipy==1.16.2
    - numpy==2.3.3
    - pandas==2.3.3
    - matplotlib==3.10.6
